### ISSUE TITLE
Delelete item button is hidden.

### ISSUE THREAD

**Issue by jbabio** [alienfamily/scanyourboxes#1]
I iPhone, if the ”Screen Zoom” is set to "Zoom”, the Delete item button is hidden. In “Normal“, you can see a thin orange/red line which alows you to delete the item.

I’ve tested the issue on an iPhone 6 (ios12) and an iPhone 8 (ios 13). Both phones behave in the same way.

Ive attached an image with screen captures side by side in both modes. hope you can fix this in a near release.

![FE08AA58-41A9-4138-932E-54AED1F584C9](https://user-images.githubusercontent.com/5908768/79820253-1d646400-838c-11ea-91f0-81d040c87ce3.png)

**Comment by alienfamily** [comment]
Hi @jbabio 

Thanks for the feedback. 
A new version is on it's way with a fix for that.
Should be available on the first week of September.
