### ISSUE TITLE
QR Code Print in Dark Mode

### ISSUE THREAD

**Issue by mrjceo17** [alienfamily/scanyourboxes#10]
Hey Remy, just a heads up, in dark mode the print QR code function doesn’t show. When I moved to light mode it worked. Thanks again for adding this feature!!
![98DAD1A8-F06A-4C1E-91F4-692EF98A70C4](https://user-images.githubusercontent.com/82677770/116296224-934d9900-a75f-11eb-8e17-8365c037320d.png)

**Comment by alienfamily** [comment]
Damn ! It's fixed and the update is submitted to Apple.

**Comment by alienfamily** [comment]
Apple has been quick this time, the update is available on the App Store.
