### ISSUE TITLE
Search should include annotation area

### ISSUE THREAD

**Issue by bgrupczy** [alienfamily/scanyourboxes#11]
Can you have the search also use the annotation/notes/comment field? That's where I would type in "tags"... for now.

My use case is not for moving to a new home but for my long term storage.

Nice app! Thanks!

**Comment by alienfamily** [comment]
Hi Brad,

Thanks for the feedback.

Annotation can contains sentences so it will bring too many words matching the search string.
Also you won't have any visual reference of your search string and the search results.
For example, if you search `for` you will have all the items with annotation containing the string `for` and you will only see the items names on the search results. 
Not sure that many people get why it works this way.

I would prefer to add "tags" in the app. It will be clearer and easier to understand for users.
