### ISSUE TITLE
Feature request - Print on standard label sizes

### ISSUE THREAD

**Issue by bgrupczy** [alienfamily/scanyourboxes#14]
Is it hard to add the ability to print to specific label sizes? Avery makes standard labels, for example:

94106 - https://www.avery.com/blank/labels/94106
94107 - https://www.avery.com/blank/labels/94107

Thanks!
Brad

**Comment by alienfamily** [comment]
It's possible to add these print format.

Is it for printing the same qr code multiple times or different qr codes?

**Comment by bgrupczy** [comment]
Sorry I missed this!
Both actually. I'd like to put a label on at least two sides. Long side and short side of container. And then be able to do that for many containers.

**Comment by alienfamily** [comment]
Thanks for the feedback and sorry for the delay. I am working on a big update if the app so I don't have much time for improvements on the current version.

You have the possibility to print up to 6 QR Codes per page in 4x6 format from the QR Code screen of your box.
<img src="https://user-images.githubusercontent.com/1974356/121035463-31e10700-c7ae-11eb-897f-d3c8641098ce.png" width="250">

Does this suit your need or do you need specific format ?

**Comment by bgrupczy** [comment]
It would have to be specific layout to fit the Avery labels I mentioned above.

It's not a rush. It would just be a really nice feature to be able to print directly onto a preformatted label. Looking forward to your new version.

**Comment by alienfamily** [comment]
With a few years late, sorry, the feature will be available in release 3.2.0 which is under Apple approval.

**Comment by bgrupczy** [comment]
Awesome! Thanks!
