### ISSUE TITLE
Putting storage lists on multiple devices

### ISSUE THREAD

**Issue by lbirkhoff** [alienfamily/scanyourboxes#15]
I used Scan Your Boxes to organize the library at the preschool I work at. I would like to get the bins to be accessible on all the teacher's devices (or at least on the program iPads). How can I get them all on multiple devices?

**Comment by alienfamily** [comment]
Hi,

You can synchronize your boxes / bins with iCloud (the cloud button on the upper left of the boxes screen).
If you want to share the boxes on multiple device then you need to use the same iCloud account on all the devices.
