### ISSUE TITLE
App keeps reverting to scanner

### ISSUE THREAD

**Issue by Goldensyrup** [alienfamily/scanyourboxes#16]
Every time one does anything else, like visit another app, go to Home Screen, allow phone to go to sleep after a minute, and then one returns to the app, it’s forgotten where you were and what you were doing. Defa to the scanner. 
So one has to scroll through the list of boxes to find the box you’re in the middle of filling! Maddening!

**Comment by alienfamily** [comment]
You're right !
It's fixed in the next version which is pending Apple approval.
