### ISSUE TITLE
Bug report - iCloud sync

### ISSUE THREAD

**Issue by HiROEKrmtDFroghere** [alienfamily/scanyourboxes#22]
Hi, I found a bug with iCloud sync. If you try to sync but have an empty inventory, it will still try to sync but will get stuck in that process. There is a cancel button on the page behind the sync notice, but no way to cancel the sync in progress. The workaround is to tap and drag up from bottom of the screen (or double press the home button if iPhone 8 or earlier), clear the app from App Switcher by swiping up, tap anywhere to leave App Switcher, and reopen Scan Your Boxes.

**Comment by alienfamily** [comment]
Hi,
Thanks for the feed back and sorry for the late reply.

It's fixed and will be available in the next release.
