### ISSUE TITLE
Printing options

### ISSUE THREAD

**Issue by elasticwax** [alienfamily/scanyourboxes#23]
Is there a way to change or customize the printing format? The way it is currently has a few problems:
1) What labels is this formatted for? The only options are a US Letter sheet or a 4x6 sheet.
2) If you print or need any less that 6 labels, you waste the remainder of the sheet since you can't position the QR code to the unused labels.
3) The labels have an extremely inefficient use of space. even if you utilize all three box descriptors, a lot of the label is empty.
4) Can we customize the label, what if I just want the QR code?
5) Can we format labels for standard Dymo or other "label printer" labels? Let's say. have a 1"x1" label roll, I'd like to just print the QR codes and select the number of labels to print off.

As it is, I don't see a good way to actually print labels. I'm going to have to do this backwards and use my label printer to make the QR codes first.

**Comment by elasticwax** [comment]
And I saw issue #14 already, but Avery labels aren't the only option, and it doesn't address the issue of partially printed sheets.

**Comment by alienfamily** [comment]
With a few years late, sorry, the feature will be available in release 3.2.0 which is under Apple approval.
