### ISSUE TITLE
Archivage de boîtes

### ISSUE THREAD

**Issue by Wobinus** [alienfamily/scanyourboxes#3]
Bonjour, 
J'utillise Scan your boxes depuis presque un an.
Or j'ai plusieurs déménagements en vue. 
Serait-il possible de créer plusieurs déménagements et passer de l'un à l'autre sans que les boites de l'un ne s'affichent en même temps que l'autre ? Ce qui reviendrait à créer plusieurs sessions de groupes de boîtes indépendantes les unes des autres.
Merci

**Comment by alienfamily** [comment]
Bonjour Wobinus,

L’application a été réalisé dans l’objectif de garder un inventaire des objets que l’on possède chez soi et de pouvoir les retrouver facilement.
Meme s’il est vrai que beaucoup d’utilisateurs l’utilisent pour leur déménagement personnel, nous préférons pour l’instant conserver l’idée d’origine de l’application.
Bonne journée
