### ISSUE TITLE
Dark Mode bugs

### ISSUE THREAD

**Issue by boxerupper** [alienfamily/scanyourboxes#4]
The app presents black text on a dark background when creating new rooms or categories of content when the phone is in dark Mode. 
![B7571A2C-672C-4CD4-99C3-CBA0D399A4E5](https://user-images.githubusercontent.com/78380410/106507605-34abb280-64c3-11eb-9a41-30fb2a06d641.png)

**Comment by alienfamily** [comment]
Thanks for the feedback. It will be fixed on the next version.

**Comment by alienfamily** [comment]
The new version 1.3.6 is available on the App Store.
