### ISSUE TITLE
Impression de listing

### ISSUE THREAD

**Issue by Wobinus** [alienfamily/scanyourboxes#6]
Bonjour, 
Serait-il possible d’ajouter une option d’ajout de vignettes des photos du contenu des boites dans les listings pdf et CSv ?
Merci 
Robin Hacquard

**Comment by alienfamily** [comment]
Bonjour,

Le fichier CSV contient du texte mais sur le PDF c'est possible.
Pour que je puisse réfléchir à un format de fichier PDF utile pour vous, pourriez-vous me décrire quel usage vous en avez ?
Par exemple, avez-vous besoin de l'imprimer ? De l'utiliser comme un inventaire ?

En fonction de vos réponses je pourrai trouver la bonnes tailles d'images, le bon nombre d'objets par page, etc.

À bientôt,

Rémy

**Comment by Wobinus** [comment]
Bonsoir,
En effet, je cherche à imprimer le pdf afin de pouvoir conserver sous forme papier l’ensemble de mes boites afin qu’une personne non équipé de l’iphone hébergeant l’application puisse visualiser relativement facilement le contenu des boîtes. Les images, que je sais en assez basse résolution n’auraient pas besoin d’être très grandes, taille timbre-poste par exemple. 
Le PDF pourrait ainsi montrer le listing avec deux colonnes, une par boite si c’était possible, afin de ne pas avoir un document trop fourni en pagination.
Cordialement
Robin

**Comment by alienfamily** [comment]
Merci pour ce retour.
Je vais y réfléchir pour une prochaine version de l'application.

Rémy

**Comment by mrjceo17** [comment]
Hey Remy, would love to see this feature on an updated version as well. Just small pictures by each item would be great. Would probably make the PDF several more pages though. Maybe you could select a pdf with or without images depending on what you need. I could see this being helpful sending the pdf to other people who don’t have the app to see what’s in the boxes.

**Comment by alienfamily** [comment]
A new version has been submited to Apple with this feature.
Should be available in 2 or 3 days.

**Comment by alienfamily** [comment]
It goes faster than I thought.
The update is available on the App Store.

**Comment by mrjceo17** [comment]
Feature works perfect, Remy! Thank you very much!

**Comment by mrjceo17** [comment]
Remy, tested both options (with and without photos) they both work great. Thanks again!

**Comment by Wobinus** [comment]
Merci pour cette mise à jour. C’est parfait.
R. H.
