### ISSUE TITLE
Cloud Backup not working

### ISSUE THREAD

**Issue by Dreadorski** [alienfamily/scanyourboxes#7]
Hi First of all thanks for updating the full box switch and box icon nice solution :)

I have issue uploading to cloud - it errors out but have plenty of storage and app is ticked for cloud access as such.

File size is about 37MB I have over 150GB free, error has occurred...free disk space on you device and on cloud and internet.

Im trying to use it on M1 Mac so importing would be great :)

**Comment by alienfamily** [comment]
Hi,

If the error is not related to internet connection or space left on iCloud, then it could be an issue when:
- the app is trying to create it's folder on iCloud
- the app can't get iCloud path to know where to store your data

A few questions to try to understand where it comes from:
- On which device do you have the error (iPhone, iPad or M1 Mac)?
- What is your OS version?
- Could you check if you have a folder "Scan Your Boxes" on your iCloud Drive? If you have the folder, do you have zip files in it?

**Comment by Dreadorski** [comment]
Error is on iPhone 12 14.4.1 - App is enabled on iCloud - no folder exists on iCloud. _Note error was no introduced in last update - didn't work prior to this either._

Further tests on Mac (M1) added a dummy box and uploaded and that worked so now have a folder.

Retested on iPhone (closed app and restarted) and error is still there.

**Comment by alienfamily** [comment]
It's weird that it works on your mac but not on your iPhone.

It could come from an issue when creating temporary files on your iPhone.
Maybe the app doesn't have the rights to write these tmp files or enough free disk space on your iPhone.

Could you check how much free disk space you have on your iPhone and how much is used by the app (settings -> general -> iPhone Storage -> Scan Your Boxes)?

If the free disk space is too low then it could comes from there.
If not, then I'm little stuck ...

**Comment by Dreadorski** [comment]
Yeah don't think its that I have 90GB free on the phone itself, App is 8.9MB using 83.4MB of data (20 boxes)

**Comment by alienfamily** [comment]
Damn, I'm a little short of ideas.
If you agree, I can try to make you a modified application that would allow me to retrieve specific logs on the error encountered.
This app would be identical to the one available on the App Store with only additional logs. None of your personal data will be sent. The app will generate a txt file from which you can copy / paste the content in the comment of the ticket.
Is it ok for you?

**Comment by Dreadorski** [comment]
Sorry for the delay work :) sure fine with me

**Comment by alienfamily** [comment]
Hi,
A debug version is ready and waiting for Apple approval.
Once Apple validate it, I will send you an invite link with the tests details.

**Comment by alienfamily** [comment]
Here is an invite link that will give you access to a debug version https://testflight.apple.com/join/L3yK6bk6

You will have to 

1. Install the TestFlight app from the App Store (made by Apple)
2. Install the Scan Your Boxes version proposed by the invite link (it will install as an update of your app so you won't loose your datas)
3. From the new app, you will launch a backup / import on iCloud and it will enable a share button. You will be able to copy / paste the logs.
![image](https://user-images.githubusercontent.com/1974356/112995833-ebe34380-916b-11eb-9f8a-7368bc0f7ca2.png)

If you want to go back on the last stable version of Scan Your Boxes, you can just install it from the App Store.

Hope it will give us enough information to resolve the issue

**Comment by Dreadorski** [comment]
[text-B690BEC75E3A-1.txt](https://github.com/alienfamily/scanyourboxes/files/6229365/text-B690BEC75E3A-1.txt)

**Comment by alienfamily** [comment]
Thx, that was fast :)
It looks like a subdirectory "Documents" exists and shouldn't be here. In fact, it should never has happened.
I have prepared a fix version to deals with subdirectories and it's under validation by Apple.

I will send you a TestFlight link for validation before officially releasing the fix version.

**Comment by alienfamily** [comment]
It's done, you can update the app with the same invite link https://testflight.apple.com/join/L3yK6bk6

**Comment by Dreadorski** [comment]
Tried no change, I also installed standard and installed from latest link again just in case same error
[text-4363A42A5E4A-1.txt](https://github.com/alienfamily/scanyourboxes/files/6234974/text-4363A42A5E4A-1.txt)

**Comment by alienfamily** [comment]
Damn, ok I made a new version that completely ignore this "Documents" folder and add some logs on files names.
Still same link https://testflight.apple.com/join/L3yK6bk6 
The new version is 1.4.3 (56)

Hope it will be ok

**Comment by Dreadorski** [comment]
Okay working almost :)

So importing back onto iPad works data wise okay all boxes and items are there, however some items have lost images, Mac import shows as working but no boxes appear after import

**Comment by alienfamily** [comment]
Your files are in an inconsistent state that shouldn't have happenned. And dealing with this inconsistent state create a high risk of breaking things for other users.

My advice would be to uninstall and reinstall the app on your iPhone to clear this inconsistent state and then create your boxes again.
I know thats hard. If you want, I can send you a version of the app that will permit you to get a zip file with all your datas so you will have the item's pictures.
Tell me if you want this version and I will do it as quickly as possible.

For Mac import, sadly I don't have a M1 Mac to test it. If you were testing the debug app, do you have the logs ?

Sorry for the bad news, I can send you some vouchers to unlock unlimited boxes for friends or family if you want.

**Comment by Dreadorski** [comment]
Just to clarify if I export to cloud and then purge app and reinstall would imported data be in consistent state then?

If that's the case I can take screen shots of the contents from the current app as such, and then the ones missing images I can just add from screen shot - aka less work.

I guess the question then is how did they get into a inconsistent state as all usage was using iPhone alone - Mac and iPad have only been used to ingest cloud data.

Re M1 you probably want to disable option to install it as Im probably not going to be the only one who thinks it useful to be able to see boxes on mac, which would be a shame but I understand why you can't support.

**Comment by alienfamily** [comment]
> Just to clarify if I export to cloud and then purge app and reinstall would imported data be in consistent state then?

Hard to tell without having access to your data. 
Can you test to delete an item without image and see if it works? If so, then you will be able to re-create them and it should be ok.
From my understanding of your configuration
1. you have made the backup from your **iPhone** (on the last debug version)
2. once imported on your **iPad** you have items without image (on App Store version)
3. you remove on your **iPhone** an item that doesn't have an image on **iPad**
4. you create it again on **iPhone** and check if after **iPhone** backup and **iPad** import the item is correctly display on the **iPad**

Thing is I really don't understand how you get into this state. Tried to reproduce the issue many times and to find where it could comes from but without success.

If you want I can be available for a call to troubleshoot that.

> Re M1 you probably want to disable option to install it as Im probably not going to be the only one who thinks it useful to be able to see boxes on mac, which would be a shame but I understand why you can't support.

You're right, thanks for the advice.

**Comment by mrjceo17** [comment]
I was having the same issue with backup not syncing to iCloud. Going to play with the 1.4.3 version and see what I can come up with.
