### ISSUE TITLE
Sync with Partner

### ISSUE THREAD

**Issue by mrjceo17** [alienfamily/scanyourboxes#8]
Hello!

First off, love this app. We are in the middle of a move and the picture taking and search functionality is fantastic. One question I had - is there a way I could sync the data for my boxes with another user? Like package and send the data so my wife can scan with her phone and see what’s in each box?

Thanks!

**Comment by alienfamily** [comment]
Hi,

Right now it's not possible to sync your boxes with another user. The feature is under development.
If you both have an iCloud account, you can connect to your iCloud drive account on you browser and download the Scan Your Boxes folder. And then, upload this folder on your wife's iCloud drive account.
She should be able to use the import feature within the app to get boxes from the copied folder.

Hope it will help you. Tell me if you need more help.

**Comment by mrjceo17** [comment]
Sounds great! Thanks for the response! Now I need to figure out how to get it to sync with iCloud. It says I have too not enough space remaining or I’m not connected to the internet when I try to sync it to iCloud. I believe I have more than enough space. I deleted the folder and tried to re sync it and it didn’t work. Any thoughts?

**Comment by mrjceo17** [comment]
Hey! So I saw the other thread and downloaded the TestFlight beta version and the cloud function worked.

**Comment by alienfamily** [comment]
Nice, I will prepare a fix version base on the TestFlight beta.
Once it will be available on the App Store, I will deactivate beta version and you will be able to use the app from the App Store.
