### ISSUE TITLE
Feature request - Print to 6 QR code grid

### ISSUE THREAD

**Issue by mrjceo17** [alienfamily/scanyourboxes#9]
Hey Remy,

Is there a way to have a print dialogue screen added where you can print at least five of the same QR code’s to the same sheet of paper directly from the app? 

This is my current workflow:
-Create a box (name it and categorize it)
-Fill said box with items
-Click on the QR code
-Screenshot the QR code
-Trim it to more of a square
-Save screenshot as image
![AE159413-821D-449A-8083-F45A147D20AE](https://user-images.githubusercontent.com/82677770/115329215-9b9e4680-a157-11eb-9c3b-46b2b55849b8.jpeg)

-Open Layout (app) 
-Select the 3x3 grid
![932D999D-71D6-44A1-840A-09A3AB897E71](https://user-images.githubusercontent.com/82677770/115329340-ca1c2180-a157-11eb-882f-bbdc2c12bbb6.jpeg)

-Save as a photo
-Open Photo App
-Click Share
-Click Print

I print to sticker paper then use a paper cutter to cut out 5 of the stickers, then I stick them on the tops and sides of my boxes. I end up wasting most of the sticker paper since I only use 5 stickers and the grid only does 9. And it prints in the center of the page so I end up wasting a whole sheet of sticker paper for one QR code. 

![842A1F7C-2D0F-44C3-8156-BBD97391ED68](https://user-images.githubusercontent.com/82677770/115329626-2b43f500-a158-11eb-9fe0-dd976e8f3dba.jpeg)

My system works well, but it would be helpful if I could print directly from the app. I only need to print 5 ~2”x2” stickers. One for the lid and one for each visible side of the box. It would be best if the stickers would print only  on the top half of an 8.5x11 sheet of printer paper, then I could print one set of QR code’s, cut them out, then reuse the other half of the paper to print another set for another box.

This is definitely a “want” and not a “need”, but if the feature could be added, it would make this app that much more awesome. 

Thanks for your support so far! Love this app!!! Side note, I use the new pdf photo feature to show inventory in the clear boxes on the side. That feature is so nice. Thanks for adding it!

-Mark

**Comment by alienfamily** [comment]
Hi Mark,

Just to let you know, the version with this new feature is still waiting for review on Apple side.
I just contact their support to ask why it's taking so much time for them to validate it.

**Comment by mrjceo17** [comment]
Sounds good! Thanks Rémy!

**Comment by alienfamily** [comment]
Finally Apple validated the app.
Version 1.4.4 is available with this feature.
